import { normalizeField, parseRedFlags, summaryDateFormatter } from './formatters.js'

export default function SummaryCard({ summary, statusTone }) {
  return (
    <article className={`card summary-card tone-${statusTone}`}>
      <header>
        <p className="eyebrow">AI-generated patient summary</p>
        <h3>{summary ? normalizeField(summary.patientName) : 'Waiting for record…'}</h3>
        <p className="meta">
          {summary?.collectedAt
            ? `Updated ${summaryDateFormatter.format(new Date(summary.collectedAt))}`
            : 'No intake timestamp'}
        </p>
        {summary && (
          <div className="tag-pill">
            <span>{normalizeField(summary.callId ?? 'Unknown call')}</span>
            <span className="divider">•</span>
            <span>{normalizeField(summary.status ?? 'open')}</span>
          </div>
        )}
      </header>

      <div className="summary-focus">
        <div>
          <p className="field-label">Severity</p>
          <span className="severity-pill">{normalizeField(summary?.severity)}</span>
        </div>
        <div>
          <p className="field-label">Symptoms</p>
          <p>{normalizeField(summary?.symptoms)}</p>
        </div>
      </div>

      <div className="summary-grid">
        <div>
          <p className="field-label">Chief complaint</p>
          <p>{normalizeField(summary?.chiefComplaint)}</p>
        </div>
        <div>
          <p className="field-label">Duration</p>
          <p>{normalizeField(summary?.duration)}</p>
        </div>
        <div>
          <p className="field-label">Associated symptoms</p>
          <p>{normalizeField(summary?.associatedSymptoms)}</p>
        </div>
        <div>
          <p className="field-label">Relevant history</p>
          <p>{normalizeField(summary?.relevantHistory)}</p>
        </div>
        <div>
          <p className="field-label">Current meds</p>
          <p>{normalizeField(summary?.currentMedications)}</p>
        </div>
        <div>
          <p className="field-label">Additional details</p>
          <p>{normalizeField(summary?.additionalDetails)}</p>
        </div>
      </div>

      <div className="redflags">
        <p className="field-label">Red flags</p>
        <ul>
          {parseRedFlags(summary?.redFlags).length === 0 && <li className="muted">No red flags reported</li>}
          {parseRedFlags(summary?.redFlags).map((flag) => (
            <li key={flag}>❌ {flag}</li>
          ))}
        </ul>
      </div>

      <p className="summary-alert">The data is generated by AI for scripting only. Please use clinical expertise before diagnosing.</p>
    </article>
  )
}
